version: '3'

services:
  backend:
    container_name: kahoot-frontend
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - '3001:8080'
    environment:
      PORT: '${PORT}'
